// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// JunoClient is the client API for Juno service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JunoClient interface {
	// Gets information about the cluster.
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type junoClient struct {
	cc grpc.ClientConnInterface
}

func NewJunoClient(cc grpc.ClientConnInterface) JunoClient {
	return &junoClient{cc}
}

func (c *junoClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/juno.proto.v1.Juno/Status", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JunoServer is the server API for Juno service.
// All implementations must embed UnimplementedJunoServer
// for forward compatibility
type JunoServer interface {
	// Gets information about the cluster.
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	mustEmbedUnimplementedJunoServer()
}

// UnimplementedJunoServer must be embedded to have forward compatible implementations.
type UnimplementedJunoServer struct {
}

func (UnimplementedJunoServer) Status(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedJunoServer) mustEmbedUnimplementedJunoServer() {}

// UnsafeJunoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JunoServer will
// result in compilation errors.
type UnsafeJunoServer interface {
	mustEmbedUnimplementedJunoServer()
}

func RegisterJunoServer(s grpc.ServiceRegistrar, srv JunoServer) {
	s.RegisterService(&Juno_ServiceDesc, srv)
}

func _Juno_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JunoServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/juno.proto.v1.Juno/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JunoServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Juno_ServiceDesc is the grpc.ServiceDesc for Juno service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Juno_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "juno.proto.v1.Juno",
	HandlerType: (*JunoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _Juno_Status_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/v1/juno.proto",
}
